### ISSUE TITLE
Problems setting up

### ISSUE THREAD

**Issue by mrVanDalo** [foxel/seafile-docker#5]
I don't use `docker-compose` I use ansible. (on the bottom is the script).

The problem is, when I run this:
```
docker exec seafile <password>
```
I get this
```
tcp://172.17.0.5:3306 is not a valid port
```
I could nail it down to this call which breaks

```
exec python2.7 setup-seafile-mysql.py auto -e 1 -n seafile -p 8082 -o mysql -u seafile -w seafile -c ccnet_db -s seafile_db -b seahub_db
```
in `/seafile/seafile-server/setup-seafile-mysql.sh auto -e 1 -n seafile -p 8082 -o mysql -u seafile -w seafile -c ccnet_db -s seafile_db -b seahub_db` from the `setup` script.

Here is the Ansible script:

```
- name: Run Mysql Container
  docker_container:
    name: seafile_mysql
    image: mysql:5.7
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ lookup('passwordstore', 'seafile/mysql/root create=true') }}"
    volumes:
      - "{{ seafile.mysql.home }}:/var/lib/mysql"
  notify:
    restart-seafile

- name: Run Seafile Container
  docker_container:
    name: seafile
    image: foxel/seafile:6.3.3
    state: started
    ports:
      - "{{ seafile.port }}:80"
    volumes:
      - "{{ seafile.home }}:/seafile"
    env:
      SEAFILE_URL: "{{ seafile.domain }}"
    links:
      - "seafile_mysql:mysql"

- name: Init Run Seafile Container
  shell: >
    docker exec seafile  \
      setup {{ lookup('passwordstore', 'seafile/mysql/root' ) }}
  args:
    creates: "{{ seafile.home }}/.installed"
  notify:
    restart-seafile
```
